"""empty message

Revision ID: 161366c2232c
Revises: ee53cd721b01
Create Date: 2021-03-24 16:41:15.987463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '161366c2232c'
down_revision = 'ee53cd721b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ej', 'cnpj',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ej', 'imagem',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ej', 'nome',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tarefa', 'descricao',
               existing_type=mysql.TEXT(collation='latin1_general_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tarefa', 'icone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tarefa', 'prazo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tarefa', 'titulo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('usuario', sa.Column('reset_token', sa.String(length=255, collation='latin1_general_ci'), nullable=True))
    op.add_column('usuario', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.alter_column('usuario', 'email',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('usuario', 'foto_trainee',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=120),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('usuario', 'login',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'senha',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'urole',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'urole',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('usuario', 'senha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'nome',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'login',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'foto_trainee',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=120),
               existing_nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.drop_column('usuario', 'token_expiration')
    op.drop_column('usuario', 'reset_token')
    op.alter_column('tarefa', 'titulo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('tarefa', 'prazo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('tarefa', 'icone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('tarefa', 'descricao',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='latin1_general_ci'),
               existing_nullable=False)
    op.alter_column('ej', 'nome',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('ej', 'imagem',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('ej', 'cnpj',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
