"""primeira_atualização

Revision ID: 28bcf08b784c
Revises: ae8d3f765e3a
Create Date: 2020-03-25 12:43:28.328251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28bcf08b784c'
down_revision = 'ae8d3f765e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('usuario', sa.Column('urole', sa.Text(length=50), nullable=False))
    op.alter_column('usuario', 'senha',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               nullable=False)
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.alter_column('usuario', 'senha',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               nullable=True)
    op.drop_column('usuario', 'urole')
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
