"""empty message

Revision ID: 2a2973b93b10
Revises: 
Create Date: 2020-07-27 19:22:37.509056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2973b93b10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('icone', sa.String(), nullable=True),
    sa.Column('prazo', sa.String(), nullable=True),
    sa.Column('ehSolo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('tarefaTrainee',
    sa.Column('id_trainee', sa.Integer(), nullable=True),
    sa.Column('id_tarefa', sa.Integer(), nullable=True),
    sa.Column('feita', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tarefa.id'], ),
    sa.ForeignKeyConstraint(['id_trainee'], ['usuario.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefaTrainee')
    op.drop_table('tarefa')
    # ### end Alembic commands ###
