"""empty message

Revision ID: 4a2cf598d5b5
Revises: b93e0966632d
Create Date: 2020-07-27 18:49:24.832942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2cf598d5b5'
down_revision = 'b93e0966632d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto_trainee', sa.String(length=120), nullable=True))
    op.add_column('usuario', sa.Column('nome', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nome')
    op.drop_column('usuario', 'foto_trainee')
    # ### end Alembic commands ###
