"""mudanca_usuario_urole(server_default)

Revision ID: 941db2d7b39d
Revises: 7764c178cf54
Create Date: 2020-03-26 13:58:17.974066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '941db2d7b39d'
down_revision = '7764c178cf54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'email',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('usuario', 'login',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'senha',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'urole',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'urole',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('usuario', 'senha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'login',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
