"""empty message

Revision ID: b93e0966632d
Revises: 
Create Date: 2020-07-17 13:11:28.698959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93e0966632d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ej',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('imagem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('urole', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('ej_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ej_id'], ['ej.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('ej')
    # ### end Alembic commands ###
