"""empty message

Revision ID: ce9e7c294125
Revises: 72f211be778b
Create Date: 2021-04-28 14:48:51.107105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce9e7c294125'
down_revision = '72f211be778b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ej', 'imagem',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('ej', 'nome',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('cnpj', table_name='ej')
    op.drop_column('ej', 'projetos_atual')
    op.drop_column('ej', 'cnpj')
    op.drop_column('ej', 'faturamento_meta')
    op.drop_column('ej', 'faturamento_atual')
    op.drop_column('ej', 'projetos_meta')
    op.alter_column('tarefa', 'descricao',
               existing_type=mysql.TEXT(collation='latin1_general_ci'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tarefa', 'icone',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tarefa', 'prazo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tarefa', 'titulo',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('usuario', 'foto_trainee',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=120),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('usuario', 'login',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'senha',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'urole',
               existing_type=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'urole',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
    op.alter_column('usuario', 'senha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'nome',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('usuario', 'login',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'foto_trainee',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=120),
               existing_nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=80),
               existing_nullable=False)
    op.alter_column('tarefa', 'titulo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('tarefa', 'prazo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=100),
               existing_nullable=True)
    op.alter_column('tarefa', 'icone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    op.alter_column('tarefa', 'descricao',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='latin1_general_ci'),
               existing_nullable=False)
    op.add_column('ej', sa.Column('projetos_meta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ej', sa.Column('faturamento_atual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ej', sa.Column('faturamento_meta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ej', sa.Column('cnpj', mysql.VARCHAR(collation='latin1_general_ci', length=100), nullable=True))
    op.add_column('ej', sa.Column('projetos_atual', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('cnpj', 'ej', ['cnpj'], unique=True)
    op.alter_column('ej', 'nome',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=False)
    op.alter_column('ej', 'imagem',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='latin1_general_ci', length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
