"""segunda_atualizacao

Revision ID: db66c5ef970d
Revises: 28bcf08b784c
Create Date: 2020-03-26 12:27:28.343552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db66c5ef970d'
down_revision = '28bcf08b784c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'active')
    # ### end Alembic commands ###
